QulixTask/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QulixTask.Models
{
    public class Company
    {
        public int id { get; set; }
        public string companyName { get; set; }
        public string companyForm { get; set; }
    }
}

QulixTask/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace QulixTask.Models
{
    public class Employee
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime employmentDate { get; set; }
        public string position { get; set; }
        public Company company { get; set; }
    }
}

QulixTask/Models/ErrorViewModel.cs
using System;

namespace QulixTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QulixTask/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using QulixTask.DB;
using QulixTask.Models;

namespace QulixTask.Controllers
{
    public class CompanyController : Controller
    {
        DbConnection dbConnection;

        public CompanyController()
        {
            dbConnection = new DbConnection();
        }

        public IActionResult Сompanies()
        {
            List<Company> companies = dbConnection.GetAllCompanies().Result;
            return View(companies);
        }

        [HttpPost]
        public IActionResult CreateCompany(Company company)
        {
                dbConnection.AddCompany(company);
                return RedirectToAction("Сompanies");            
        }

        [HttpGet]
        public IActionResult DeleteCompany(int id)
        {
            dbConnection.DeleteCompany(id);
            return RedirectToAction("Сompanies");
        }

        [HttpPost]
        public IActionResult UpdateCompany(Company company)
        {
            dbConnection.UpdateCompany(company);
            return RedirectToAction("Сompanies");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QulixTask/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QulixTask.DB;
using QulixTask.Models;

namespace QulixTask.Controllers
{
    public class EmployeeController : Controller
    {
        DbConnection dbConnection;
        public EmployeeController()
        {
            dbConnection = new DbConnection();
        }
        public IActionResult Employees()
        {
            List<Company> companies = dbConnection.GetAllCompanies().Result;
            ViewBag.companies = companies;
            return View(dbConnection.GetAllEmployees().Result);
        }
        public IActionResult CreateEmployee(Employee employee)
        {
            dbConnection.AddEmployee(employee);
            return RedirectToAction("Employees");
        }
        public IActionResult DeleteEmployee(int id)
        {
            dbConnection.DeleteEmployee(id);
            return RedirectToAction("Employees");
        }

        public IActionResult UpdateEmployee(Employee employee)
        {
            dbConnection.UpdateEmployee(employee);
            return RedirectToAction("Employees");
        }
    }
}

QulixTask/Views/Company/Сompanies.cshtml
@model List<QulixTask.Models.Company>

@{
    ViewData["Title"] = "Companies";
}

<h1 class="display-4 text-center">@ViewData["Title"]</h1>

<input type="button" class="btn btn-primary" value="Добавить компанию" id="btnAddCompany" />

@*Форма для добавления компании, открывается по нажанию кнопки "Добавить компанию" и закрывается при нажании "Отмена".
    При добовлении происходит переадресация на эту же страницу для того чтобы отобразить добавленные данные.*@

<form class="mt-5 mb-5 hide_form" action="/Company/CreateCompany" method="post" id="addCompanyForm">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Идентификатор (устанавливается автоматически)" readonly name="id" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Наименование компании" required maxlength="250" name="companyName" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Организационно-правовая форма" required maxlength="20" name="companyForm" />
    </div>
    <div class="row">
        <div class="col">
            <input type="submit" class="btn btn-success btn-block" value="Сохранить" />
        </div>
        <div class="col">
            <input type="button" class="btn btn-danger btn-block" value="Отмена" id="btnAddCompanyCancel" />
        </div>
    </div>
</form>


@*Форма для обновления информации о компании, открывается по нажанию кнопки "Изменить" в таблице и закрывается при нажании "Отмена".
    При обновлении происходит переадресация на эту же страницу для того чтобы отобразить обновленные данные.*@

<form class="mt-5 mb-5 hide_form" action="/Company/UpdateCompany" method="post" id="updateCompanyForm">
    <div class="form-group">
        <input id="inpUpdateId" type="text" class="form-control" placeholder="Идентификатор (устанавливается автоматически)" readonly name="id" />
    </div>
    <div class="form-group">
        <input id="inpUpdateCompanyName" type="text" class="form-control" placeholder="Наименование компании" required maxlength="250" name="companyName" />
    </div>
    <div class="form-group">
        <input id="inpUpdateCompanyForm" type="text" class="form-control" placeholder="Организационно-правовая форма" required maxlength="20" name="companyForm" />
    </div>
    <div class="row">
        <div class="col">
            <input type="submit" class="btn btn-success btn-block" value="Сохранить изменения" />
        </div>
        <div class="col">
            <input type="button" class="btn btn-danger btn-block" value="Отмена" id="btnUpdateCompanyCancel" />
        </div>
    </div>
</form>

<table class="table table-hover mt-5">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Наименование
            </th>
            <th>
                Организационно-правовая форма
            </th>
            <th>
                #
            </th>
            <th>
                #
            </th>
        </tr>
    </thead>
    @foreach (Company company in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelCompany => company.id)
            </td>
            <td>
                @Html.DisplayFor(modelCompany => company.companyName)
            </td>
            <td>
                @Html.DisplayFor(modelCompany => company.companyForm)
            </td>
            <td>
                @Html.ActionLink("Удалить", "DeleteCompany", new { id = company.id }, htmlAttributes: new { @class = "btn btn-danger" })
            </td>
            <td>
                <input class="btn btn-info btnUpdate" type="button" value="Изменить" />
            </td>
        </tr>
    }
</table>

QulixTask/Views/Employee/Employees.cshtml
@model List<QulixTask.Models.Employee>
@{
    ViewData["Title"] = "Employees";
}

<h1 class="display-4 text-center">@ViewData["Title"]</h1>

<input type="button" class="btn btn-primary" value="Добавить работника" id="btnAddEmployee" />

<form class="mt-5 mb-5 hide_form" action="/Employee/CreateEmployee" method="post" id="addEmployeeForm">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Идентификатор (устанавливается автоматически)" readonly name="id" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Имя" required maxlength="30" name="name" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Фамилия" required maxlength="30" name="surname" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Отчество" required maxlength="30" name="patronymic" />
    </div>
    <div class="form-group">
        <input type="date" class="form-control" placeholder="Дата приема на работу" required name="employmentDate" />
    </div>
    <div class="form-group">
        <select class="form-control" id="listPosition" name="position">
            <option label="Разработчик" value="Разработчик"/>
            <option label="Тестировщик" value="Тестировщик"/>
            <option label="Бизнес-аналитик" value="Бизнес-аналитик"/>
            <option label="Менеджер" value="Менеджер"/>
        </select>
    </div>
    <div class="form-group">
        <select class="form-control" id="listPosition" name="company.id">
            @foreach (Company company in ViewBag.Companies)
            {
                <option label="@company.companyForm '@company.companyName'" value="@company.id"/>
            }
        </select>
    </div>
    <div class="row">
        <div class="col">
            <input type="submit" class="btn btn-success btn-block" value="Сохранить" />
        </div>
        <div class="col">
            <input type="button" class="btn btn-danger btn-block" value="Отмена" id="btnAddEmployeeCancel" />
        </div>
    </div>
</form>



<form class="mt-5 mb-5 hide_form" action="/Employee/UpdateEmployee" method="post" id="updateEmployeeForm">
    <div class="form-group">
        <input id="updateEmplId" type="text" class="form-control" placeholder="Идентификатор (устанавливается автоматически)" readonly name="id" />
    </div>
    <div class="form-group">
        <input id="updateEmplName" type="text" class="form-control" placeholder="Имя" required maxlength="30" name="name" />
    </div>
    <div class="form-group">
        <input id="updateEmplSurname" type="text" class="form-control" placeholder="Фамилия" required maxlength="30" name="surname" />
    </div>
    <div class="form-group">
        <input id="updateEmplPatronymic" type="text" class="form-control" placeholder="Отчество" required maxlength="30" name="patronymic" />
    </div>
    <div class="form-group">
        <input id="updateEmplDate" type="date" class="form-control" placeholder="Дата приема на работу" required name="employmentDate" />
    </div>
    <div class="form-group">
        <select id="updateEmplPosition" class="form-control" name="position">
            <option label="Разработчик" value="Разработчик" />
            <option label="Тестировщик" value="Тестировщик" />
            <option label="Бизнес-аналитик" value="Бизнес-аналитик" />
            <option label="Менеджер" value="Менеджер" />
        </select>
    </div>
    <div class="form-group">
        <select id="updateEmplCompany" class="form-control" name="company.id">
            @foreach (Company company in ViewBag.Companies)
            {
                <option label="@company.companyForm '@company.companyName'" value="@company.id" />
            }
        </select>
    </div>
    <div class="row">
        <div class="col">
            <input type="submit" class="btn btn-success btn-block" value="Сохранить изменения" />
        </div>
        <div class="col">
            <input type="button" class="btn btn-danger btn-block" value="Отмена" id="btnUpdateEmployeeCancel" />
        </div>
    </div>
</form>


<table class="table table-hover mt-5">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Имя
            </th>
            <th>
                Фамилия
            </th>
            <th>
                Отчество
            </th>
            <th>
                Дата приема на работу
            </th>
            <th>
                Должность
            </th>
            <th>
                Компания
            </th>
            <th>
                #
            </th>
            <th>
                #
            </th>
        </tr>
    </thead>
    @foreach (Employee employee in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(empl => employee.id)
            </td>
            <td>
                @Html.DisplayFor(empl => employee.name)
            </td>
            <td>
                @Html.DisplayFor(empl => employee.surname)
            </td>
            <td>
                @Html.DisplayFor(empl => employee.patronymic)
            </td>
            <td>
                @Html.DisplayFor(empl => employee.employmentDate)
            </td>
            <td>
                @Html.DisplayFor(empl => employee.position)
            </td>
            <td>
                @Html.DisplayFor(empl => employee.company.companyForm) '@Html.DisplayFor(empl => employee.company.companyName)'
            </td>
            <td>
                @Html.ActionLink("Удалить", "DeleteEmployee", new { id = employee.id }, htmlAttributes: new { @class = "btn btn-danger" })
            </td>
            <td>
                <input class="btn btn-info btnUpdateEmpl" type="button" value="Изменить" />
            </td>
        </tr>
    }
</table>

QulixTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QulixTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="Employees">QulixTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Employees">Работники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Сompanies">Компании</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>